name: T

on:
  push:
    branches:
      - 'main'

jobs:
  github-branches-and-tags:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
     - name: Echo Tag
       run: |
         echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
         echo "Tag name from github.ref_name: ${{  github.ref_name }}"
