name: T

on:
  push:
    tags:
      - '*'

jobs:
  github-example-tags:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
     - name: GitHub Tag Name example
       run: |
         echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
         echo "Tag name from github.ref_name: ${{  github.ref_name }}"
